name: Publish packages

on:
  push:
    tags:
    - 'v*'

jobs:
  assets:
    name: Release packages
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: Check out src from Git
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Lower version of glibc is always compatible with greater version
      # So the binary will we runnable on probably all linux stable/LTS distros
      # https://pyinstaller.readthedocs.io/en/stable/usage.html#making-gnu-linux-apps-forward-compatible
      # So I use a custom python image with pyinstaller on centos7 (glibc 2.17)
      - name: Build package for GNU/Linux
        if: matrix.os == 'ubuntu-latest'
        uses: ahmet2mir/docker-python@master
        with:
          make_args: init_pip archive-linux

      - name: Upload Release Asset
        uses: ahmet2mir/softprops-action-gh-release@v1
        with:
          files: |
            ./artifacts/archives/*.tar.gz
            ./artifacts/checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

